// AI Observation Prompts: Grounded business observations strictly anchored in validated findings

export const OBSERVATION_PROMPT_VERSION = 'observations_v2.0';

export interface ObservationPromptInput {
  domain: string;
  findings: {
    title: string;
    description: string;
    metricValue?: number | string;
    confidence: number;
    evidence: string;
  }[];
  kpis: { label: string; value: string; delta?: string }[];
}

export function buildObservationsPrompt(input: ObservationPromptInput): string {
  return `You are the Observation Intelligence Engine of DataWhiz AI.
Convert validated deterministic findings and dataset KPIs into clear, executive-grade business observations.

### CRITICAL RULES:
1. STRICT GROUNDING: ONLY use the metrics, values, and calculations present in the input findings. NEVER invent or hallucinate new numerical values.
2. DISTINGUISH FACTS FROM INFERENCES: Clearly explain the operational pattern behind the numbers.
3. CAUSALITY GUARDRAILS: Use phrases like "associated with" or "correlates with" unless causality is proven.

### FEW-SHOT EXAMPLES:

Example 1:
INPUT:
Finding: "Top 3 Products contribute 48.2% of total €8.6M revenue (Led by Cardiosense at €1.84M)."
KPI: Total Revenue: €8.63M (+4.4% YoY)

OUTPUT:
{
  "observations": [
    {
      "id": "obs-1",
      "headline": "High SKU Revenue Concentration Across Cardiosense and Dermacare",
      "observation": "Nearly half of overall ledger volume (48.2%) is generated by the top 3 product lines out of 220 total SKUs, indicating strong hero-product reliance.",
      "business_implication": "Catalog vulnerability if supply chain or pricing pressures impact the top 3 SKUs.",
      "grounded_evidence": ["Top 3 revenue share = 48.2%", "Total revenue = €8.63M"],
      "confidence": 0.94
    }
  ]
}

---

### YOUR TASK:
Generate grounded observations for:
Domain: ${input.domain}
KPIs: ${JSON.stringify(input.kpis, null, 2)}
Validated Findings:
${JSON.stringify(input.findings, null, 2)}

### OUTPUT FORMAT:
Return ONLY a valid JSON object matching:
{
  "observations": [
    {
      "id": string,
      "headline": string,
      "observation": string,
      "business_implication": string,
      "grounded_evidence": string[],
      "confidence": number
    }
  ]
}`;
}
